### ISSUE TITLE
Rewrite rule with ISS

### ISSUE THREAD

**Issue by mills217** [uvdesk/community-skeleton#142]
Has anyone got UVDesk working with IIS? The rewrite rules seem to cause 404 errors. Leaving the rewrite rules out causes similar issues.

**Comment by mills217** [comment]
I've resolved this by importing the rewrite rules and then moving the web.config file to the public folder. Hopefully this helps someone else

**Comment by syukfa** [comment]
Hi. i would like to install uvdesk on IIS. Can you refer me the guide for the installation?

**Comment by Komal-sharma-2712** [comment]
> Hi. i would like to install uvdesk on IIS. Can you refer me the guide for the installation?

Currently, **Uvdesk installation with the IIS platform** is not available. It will be possible for you to **share any documentation of setting up the IIS platform** itself as I'm not very well familiar with the platform and would appreciate any relevant materials to help me get set up. So that we are tried and in the future, we can provide the guide with the IIS platform.
