### ISSUE TITLE
Permission error when add attachment

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#150]
**Environment:**
downloaded project for php -v 7.2 zip

![Screenshot7](https://user-images.githubusercontent.com/43210406/56970460-c9fa7400-6b84-11e9-8eb0-c9b33e9c2174.png)

**Comment by shubhwebkul** [comment]
Hi Vaishali,
whenever you upload an attachment, uvdesk uploads that attachment in a specific directory ( uvdesk will make that directory if not already exists.)

So here uvdesk is throwing exception because it don't have permission to make directories.
All you need to do is, allow permission to make directories.
To know, how to allow permission, you could get help [here](https://stackoverflow.com/questions/5246114/php-mkdir-permission-denied-problem).
