### ISSUE TITLE
Is the public folder required after uvdesk install ?

### ISSUE THREAD

**Issue by iGitnow** [uvdesk/community-skeleton#153]
I have successfully installed UVdesk on my server. However, the "public" folder is still accessible from the outside world. How required is it to keep it once the install is done ? If it is required, what are your recommendations to block access to this folder so that no one can run the setup process again ?

Thank you.

**Comment by vaishaliwebkul** [comment]
Hello iGitnow,

-   **the "public" folder is still accessible from the outside world?**
 Yes , the accessbility of public folder is required
   

- **If it is required, what are your recommendations to block access to this folder so that no one can run the setup process again ?**

      
Once you have completed your installation with UVDesk then you can redirect all the requests from web installer to knowledgebase panel by adding a route in file uvdesk.yaml resides in routes folder under config directory, that's how you could restrict the installer part.

Redirection route to be added in uvdesk.yaml (with proper indentation):-
**_uvdesk_support_center_bundle_use_locale:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /en/
        permanent: true_**

![uvdeskissue](https://user-images.githubusercontent.com/43210406/58161445-e712f600-7c9d-11e9-9812-a64566f653b7.png)

**Comment by iGitnow** [comment]
Thank you very much. Issue resolved.
