### ISSUE TITLE
Server Requirements

### ISSUE THREAD

**Issue by kvnsmn** [uvdesk/community-skeleton#155]
Hello,

I am trying to make the UVdesk opensource ticketing system work in our environment, but somehow I can't make it work. 

I have it running on centos 7 for testing purposes with 100gb hard drive and 4gb ram and 2x3.2ghz processors. It is slow, everytime when I want to set up the installer with http://localhost/uvdesk/public/ it won't work and open up a 500 error. Other directories are working fine.  (Then open your browser and and browse to the server domain name then go to public URL . (In my case URL is: http://localhost/uvdesk/public/)

I used the search here in issues and on their website.

A few questions:
What are the server hardware requirements? (We would like to use centos 7)
Is there a step by step guide to install uvdesk? A better one than https://www.uvdesk.com/en/blog/installation-open-source-helpdesk-uvdesk/ This one does not help at all. Even the one for MacOS or windows? did not help. There are so many steps missing.

Thanks

**Comment by UVvidu** [comment]
Hi kvnsmn,

I have it running on centos 7 for testing purposes with 100gb hard drive and 4gb ram and 2x3.2ghz processors. It is slow, everytime when I want to set up the installer with http://localhost/uvdesk/public/ it won't work and open up a 500 error. Other directories are working fine. (Then open your browser and and browse to the server domain name then go to public URL . (In my case URL is: http://localhost/uvdesk/public/)

**>> Browse your Installed Helpdesk's public folder then share the screenshot of the error with composer.lock file so that we can look into the matter to  - find the exact issue and provide you solution accordingly.**

What are the server hardware requirements? (We would like to use centos 7)

**>> Processor: 1.60GHz or higher
      RAM: 3GB or higher**

Is there a step by step guide to install uvdesk? 
**>> Steps will remain same** - https://www.uvdesk.com/en/blog/open-source-helpdesk-installation-on-wamp/

**The all you need to have structuring below:
1 - PHP 7 or Higher
2 - Composer
3 - Pre-installed IMAP & MAILPARSE PHP Extensions
4 - Server - Apache**


Do let us know for any further help.

**Comment by estebanyque** [comment]
I'm trying to install it in Centos 7 with PHP 7.2, a remote MariaDB database correctly configured under .env file, but when I opened the browser I got the message "An unexpected error occurred during the PHP version verification process. "

SeLinux is permisive, the value of the boolean httpd_can_network_connect_db is ON, the owner of the folder is apache:apache (checked against the httpd conf file).

Composer has been installed manually, PHP7.2 came from REMI repos, so, everything looks fine but I cannot run UVDesk. PHP requirements were installed.

Any ideas?

**Comment by vaishaliwebkul** [comment]
Hello **estebanyque,**

Web server might don't have permission to allow overriding of the Apache config on a per-directory basis

**Resolve Issue**
In httpd.conf , Allow Override needs to be set to All for the directory block as mention below:

**<Directory /home/users/var/www/htdocs>
	Options Indexes FollowSymLinks
	AllowOverride All
	Require all granted
</Directory>**

Reference this solution for better guide:
https://github.com/uvdesk/community-skeleton/issues/143

**Comment by estebanyque** [comment]
Thank you so much!!!

I will write it down for my own documentation!!!

Thanks again!

**Comment by vaishaliwebkul** [comment]
Hi @estebanyque

I'm glad to hear that issue resolve :)
