### ISSUE TITLE
Uvdesk docker container returning page with Internal Server Error

### ISSUE THREAD

**Issue by TatendaKwaramba** [uvdesk/community-skeleton#228]
**Description**  

**How to reproduce**  

**Possible Solution**  

**Additional context**

**Comment by vaishaliwebkul** [comment]
Hello @TatendaKwaramba,
    Please share the log file by running the **docker logs container_id**

You can reopen the issue if it still exists.

**Comment by TatendaKwaramba** [comment]
Hi vaishaliwebkul,

Thanks for getting back to me. I have commented on the issue with log file
and screenshot.

**Comment by karthickcse86** [comment]
Hi Team,

Is this issue resolved since I too facing the same error and below are the docker container logs for your reference.

 * Stopping MySQL database server mysqld                                                                                                                                     [ OK ] 
 * Restarting Apache httpd web server apache2                                                                                                                                       AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
                                                                                                                                                                             [ OK ]
 * Stopping MySQL database server mysqld                                                                                                                                     [ OK ] 
 * Starting MySQL database server mysqld
