### ISSUE TITLE
Feature request: link/refer two or more tickets

### ISSUE THREAD

**Issue by laurentiu2** [uvdesk/community-skeleton#241]
**Description**  
Although I'm quite a new user of uvdesk community edition, I can see how important it is to link a ticket to another one/ones if they are related.
For example in order to solve a ticket (t1) it has to be opened a new one (t2), and this  new one needs to be solved first. So some reference has to be mentioned inside ticket t1.
Or if a ticket is duplicate of another (for the same customer) it has to be closed and referred inside the first one, or if a ticket depends of another one, and so on..
Similar to github.

Congrats to all developers, great job!

**Comment by papnoisanjeev** [comment]
@laurentiu2 

**>> For example in order to solve a ticket (t1) it has to be opened a new one (t2), and this new one needs to be solved first. So some reference has to be mentioned inside ticket t1.**

There is no direct link of other tickets in ticket view for now but we will see the possibilities for this.

But you can see count of all tickets of a customer in ticket view and after click on count you can see all tickets of that particular customer and see all other ticket of customer in ticket list.


![moreTicket](https://user-images.githubusercontent.com/42460055/73422642-9cc73600-434f-11ea-9d67-17e4859d6ed9.png)

**Comment by laurentiu2** [comment]
There's no problem to see **all tickets** of a customer (from list view or elsewhere) but when you have 20+ tickets for the same customer is time consuming to search for the one/ones related between them.
Another agent can't tell which one are related.
For sure you understand what I meant; this is just a feature request, an idea, not an issue or a bug.
Regards,

**Comment by papnoisanjeev** [comment]
@laurentiu2 

Sure, we would like to implement such feature for easiness of user for ticket management in future.
Thanks for your suggestion.

**Comment by papnoisanjeev** [comment]
@laurentiu2 

The most awaited and essential helpdesk application - **Customer Previous Ticket** App is now available on our store.

**Supported Version:**
UVDesk opensource version:  **1.0.12**

For more details refer this link - https://store.webkul.com/customer-previous-tickets-uvdesk-open-source.html
