### ISSUE TITLE
Basic actions with ticket by email

### ISSUE THREAD

**Issue by imennodenis** [uvdesk/community-skeleton#258]
Hi!
It would be great to have an option to make some basic ticket actions by email.

For example, an agent can send an email with **#close** command to close a ticket by email. Or **#note** command to add a comment to the ticket.

We've being using Spiceworks for some time and this feature was very handy. You can check more detailed description of this feature here https://community.spiceworks.com/support/help-desk-server/docs/customize-and-work. It is called Tickets Anywhere, see at the end of the page.

Maybe we can already implement something like this in UVdesk with Workflows? For example, If an email has "#close" text in it, then Close the ticket. But what about "Note" feature? Maybe I'm missing something.

Thanks!

**Comment by Himaniwebkul** [comment]
@arddg 
Absolutely Yes!!! It can also be done in UVdesk with the help of an automated workflow. 
**How?** 
Refer to this workflow structure - https://prnt.sc/s46il3 or you may perform further action as required in the workflow.
Thank You!!

**Comment by arddg** [comment]
Yes, "close" action is pretty easy to implement :) Your screenshot just confirms my assumption.
But what about adding a Note? I mean internal Note for Agents. This workflow should add a Note from email's body. And also do not send any notifications to Users.

**Comment by Himaniwebkul** [comment]
@arddg 
You can also perform this action through auto workflow, may this screenshot will help you - https://prnt.sc/s4e9xh to do the same.

**Comment by papnoisanjeev** [comment]
@arddg 
You can add an internal note by email with the help of selecting conditions in workflows.
But it is not possible as per current structure to stop sending notification when you are adding a note with the help of email.
We will check the feasibility with our system if we can do this without affecting other actions.

**Comment by arddg** [comment]
But in your example Note text is static. The Note text should be added from email's body message.
Do you have some variables like %email-body% ? We could put such variable in that workflow as Note text.

**Comment by Himaniwebkul** [comment]
@arddg Currently, this functionality is not included in notes. We'll try to update this in our upcoming release. You may wait till then and keep stay with us.

**Comment by arddg** [comment]
Great! Thanks!

**Comment by papnoisanjeev** [comment]
@arddg 

We have updated the code for **note** now you can make it dynamic.

It will reflect in next release but till then you can do few changes to make it working for your project.

locate path in your project **vendor->uvdesk->core-framework->Services->TicketService.php**

Replace code of TicketService.php form here:  https://github.com/uvdesk/core-framework/blob/master/Services/TicketService.php

**Comment by arddg** [comment]
Wow! Really good news :)
What value should I put in a Note field while creating a workflow?

**Comment by papnoisanjeev** [comment]
@arddg 

Make a workflow for ticket Update.
Now set a action Add Note.

Write below content in text box:

Agent
{%ticket.agentName%}
updated ticket status.

Check this:  https://prnt.sc/s5axxb
Now update the status from Ticket View  :  https://prnt.sc/s5azkm

And a note will add with assigned agent name in place of **{%ticket.agentName%}**.

**Comment by papnoisanjeev** [comment]
@arddg 

Check this also it will help you to select all predefined words so that you can use in Note:  https://prnt.sc/s5b5tc

**Comment by arddg** [comment]
@papnoisanjeev 
Thanks! Now I understand which values I can use.

I have started to test it but I think something is wrong.
When a user creates a ticket by email, a new ticket is created and notification email is sent to admin. If admin replies this notification email right from his email client - a new ticket is created rather than adding a comment to current ticket.
Or maybe I'm missing a concept how UVdesk works? Maybe admins (agents) should reply only from web-interface?

**Comment by papnoisanjeev** [comment]
@arddg 
> I have started to test it but I think something is wrong.
When a user creates a ticket by email, a new ticket is created and notification email is sent to admin. If admin replies this notification email right from his email client - a new ticket is created rather than adding a comment to current ticket.
Or maybe I'm missing a concept how UVdesk works? Maybe admins (agents) should reply only from web-interface?

For now you can use web-interface for admin and agent to reply for a ticket.
But will check if there is any problem If replying from their email id.

**Comment by arddg** [comment]
Hello again!
We have paused our implementation process of UVdesk as our helpdesk system for several months. But now we are back to it :)
I have installed it from scratch, but we still have the problem I described above.
If admin replies notification email right from his email client - a new ticket is created rather than adding a comment to current ticket.
Any other helpdesk systems I've seen just add admin's reply to the ticket defined in email's subject. So for me such UVdesk's behavior is completely unexpectable.
User's email replies are added to the defined ticket just fine. So I think admin's replies should do the same.
Can we do something with it?
Thanks!

**Comment by papnoisanjeev** [comment]
@imennodenis 

This issue is already fixed are you still facing the same with current [release](https://github.com/uvdesk/community-skeleton/releases/tag/v1.0.13).
If yes you can reply on same thread.

**Comment by imennodenis** [comment]
Hi! Just made a fresh installation of 1.0.18 version and the situation is still the same. Maybe even worse. Now even users's email replies create a new ticket!
Let me describe all steps.
- user sends a new email (ticket) to helpdesk address
- user gets notification email that his ticket was received
- agent gets an email that a new ticket is created (by the way, system admin does not receive such email, but I have edited workflow and selected to notify admin too!)
- if user or agent reply this notification email - a new ticket is created rather that add a comment to existing one

In my opinion all email replies that have same email subject (and ticket number in it) should be added to the same ticket!
