### ISSUE TITLE
first new rule in workflow and email sending stopped working

### ISSUE THREAD

**Issue by caww** [uvdesk/community-skeleton#262]
# Bug report

### Title
**Just a quick sentence to brief your trouble with UVDesk or something associated with it.**
**Please be calm, short and emphasize on points.**

### Issue Description
**Description helps the developers to understand the bug. It describes the problem encountered or some after effect of some kind.**

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version. - current
    2. php7.3 + nginx.

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. install clean new uvdesk
    2. add smtp and imap settings - working ok - tested - email to ticket working
3. add new workflow rule for ticket created with condition contains word in email body and with sending email to agent with special email template (previosly created)
4. send email to mailbox and run cron 
5. ticket will be created but no email notifications anymore to anybody

### Expected result
**Tell us what should happen.**

*   email notificcation must be sent

### Actual result

>    **Tell us what happens instead.**

* no notifications to agent and no one to customer

**Comment by papnoisanjeev** [comment]
@caww 

Please specify the conditions you have placed in workflow with screenshot. 
so that we can test the same.

**Comment by caww** [comment]
event- ticket created
condition only one -- if description contains qqqq 
result action -- send email to agent about assigned ticket

**Comment by papnoisanjeev** [comment]
@caww 
locate path in your project.

**vendor->uvdesk->automation-bundle->EventListener->WorkFlowListner.php**

Open **WorkFlowListner.php** Now go to line 201 and change this line as [here](https://github.com/uvdesk/automation-bundle/blob/master/EventListener/WorkflowListener.php#L201).

**Comment by papnoisanjeev** [comment]
@caww 

Is your issue resolved after doing above change in your project?

**Comment by caww** [comment]
No - issue not fixed
When i implement your fix then code working like this:
if any messages received and fetched then only email go to customer and no registration emails anymore to customer
and email to agent not go at all and if string found too

but if string qqqq found in the body of received email then no one email sent
not to customer and not to agent at all

**Comment by papnoisanjeev** [comment]
@caww 

>if any messages received and fetched then only email go to customer and no registration emails anymore to customer.

Registration mail only work first time for customer from the next time only ticket generate mail will go to customer. 

> and email to agent not go at all and if string found too.

As you can see in workflow set when a ticket generate then it will assign to response performing agent(means if a agent generating a ticket on the behalf of a customer) and then email goes to that agent.
In your case your are most probably generating ticket from customer panel or direct email so there is no response performing agent  and no agent getting email for this.
Although you can select a agent in ticket create workflow whom you want to notify once a ticket generate by a customer.

>but if string qqqq found in the body of received email then no one email sent
not to customer and not to agent at all.

AS you added if condition string qqqq found in the body  then no further action will work so because of it no one getting any emails.

**Comment by caww** [comment]
No - logic is curently working is wrong
Because if workflow contant my rule with every ticket received with qqqq in description notify to agent about ticket assigned
but no one email is coming if string qqqq found - not to customer and not to agent at all
its wrong logic
must be if qqqq found then send to agent email
