### ISSUE TITLE
Issues with Italian translations

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#284]
![SharedScreenshot 1](https://user-images.githubusercontent.com/5006150/87531174-9e807e00-c691-11ea-82c5-ad37e31fd532.jpg)
![SharedScreenshot](https://user-images.githubusercontent.com/5006150/87531175-9f191480-c691-11ea-89a8-6a056544099f.jpg)

Registrati should be Accedi. Is not correct to call Registrati but must be Accedi.
The sentence "Se hai mai contattato il nostro supporto in precedenza, il tuo account sarebbe già stato creato." is not correct, should be:

"Se ci hai già contattati in precedenza l'account è già stato creato."

I suggest also to add in all languages the indication to the user if the account exist can be recovered.

So:
"If you've ever contacted our support previously, your account would have already been created, you can recover it with the forgot password function." "Se ci hai già contattati in precedenza l'account è già stato creato, puoi recuperarlo tramite la funzione di recupero password."

In the screenshot you can see some missed translation part in articles and knowledge.

**Comment by papnoisanjeev** [comment]
@PeopleInside 
If some translation are missing or incorrect you can correct it for your language.
All translation files are under **translations** folder of project.

You can correct it for Italian **(messages.it.yml)** file.

![translation](https://user-images.githubusercontent.com/42460055/87536622-00071380-c6b7-11ea-9803-ffd62599cad5.PNG)


Also create a pull request for the same so that we can also correct file and add it into project.

for Italian you can check below file:
https://github.com/uvdesk/community-skeleton/blob/master/translations/messages.it.yml

**Comment by PeopleInside** [comment]
How to add string that are not present, are not translated?

**Comment by papnoisanjeev** [comment]
@PeopleInside 

Simply add a new line (only string present in project can be translated by this way).

**"I am new here": "sono nuovo qui"**
