### ISSUE TITLE
database creation 500 status - error

### ISSUE THREAD

**Issue by ashraf-kabir** [uvdesk/community-skeleton#306]
# Bug report

#### While creating the database the it is showing 500 status

![500 error](https://user-images.githubusercontent.com/30576323/94549270-c4bac080-0273-11eb-8b79-ee23edae8236.PNG)

### Issue Description
While creating the database for the first time it is giving 500 status on xhr  500	./wizard/xhr/load/migrations

**Comment by papnoisanjeev** [comment]
@ashraf-kabir 

You can click on this post xhr request it will show you the error.

Apart from this it is most probably due to two reason only.

1. **.env** file of project have no access for read and write so enable permission first (chmod -R 777 ./path for .env file).
2. Due to less execution time in **php.ini** file you can increase it also. By default it is 30 sec so you need to increase it as well.

Finally restart your server and again try to setup.

**Comment by ashraf-kabir** [comment]
@papnoisanjeev 

note: windows user

Should I increase the max execution time?

![image](https://user-images.githubusercontent.com/30576323/94550662-eae16000-0275-11eb-8468-3ce4cb3f6e13.png)

**Comment by papnoisanjeev** [comment]
@ashraf-kabir 

Yes make it 300 and restart your server.
And then try again.
