### ISSUE TITLE
Email settings are not updating after installing uvdesk on the Website

### ISSUE THREAD

**Issue by ashraf-kabir** [uvdesk/community-skeleton#309]
# Bug report

### Email settings are not updating after installing uvdesk on the Website

![image](https://user-images.githubusercontent.com/30576323/94816732-0b4c1e80-041e-11eb-8caf-aa678aebe8f8.png)

### Issue Description
after adding the swift mailer the email settings are not updating

**Comment by manjunathpm** [comment]
Even I am having the same issue.

**Comment by manjunathpm** [comment]
The above error got solved by adding this line on .htaccess
`Require all granted`

**Comment by ashraf-kabir** [comment]
@manjunathpm no brother, it didn't work.

**Comment by papnoisanjeev** [comment]
@ashraf-kabir 

Check your console first it will show you the error for post request.

Most probably  it is due to file permission you need to enable  read/write(By **Chmod -R 777 ./file path**) access for **uvdesk.yaml, swiftmailer.yaml and uvdesk_mailbox.yaml** file under **config->packages** of your project.

**Comment by ashraf-kabir** [comment]
@papnoisanjeev but it is hosted on the web

**Comment by papnoisanjeev** [comment]
@ashraf-kabir 

You need to ask your hosting provider to provide **read/write** permission for files under **config->packages** 
If you are unable to do so.

**Comment by ashraf-kabir** [comment]
@papnoisanjeev so is this the reason behind not sending/receiving email?

**Comment by papnoisanjeev** [comment]
@ashraf-kabir 

Yes, It is possible as you are not able to update your email setting due to file permission issue so email part is not working on your helpdesk you can see error on your console when updating email setting in post request.

Provide the permission to files as suggested previously and then update email setting and try.

**Comment by PeopleInside** [comment]
Hi, I had the same issue.
Are you using special character in email or password?

I never know well how I resolved this issue but I have this issue every time I setup UVdesk.

Also I don't think the UVdesk guide and suggestion from the team to give file permission to 777 is a good idea as in my knowledge giving file permission to 777 can create security issues.

**Comment by PeopleInside** [comment]
This issue is caused by the need to clear cache from SSH console.
https://github.com/uvdesk/community-skeleton/issues/382

**Comment by chanpilli** [comment]
how to enable permissions on windows

**Comment by PeopleInside** [comment]
@chanpilli what permission?
I'm on linux (Centos) so I may be unable to help you.
Do you mean file permission? Are you facing any issue for asking this?

**Comment by chanpilli** [comment]
Hi Bro,

Thanks for your super response. Fetching/converting mails but not getting
to the portal. I have it installed on windows. Struggling to find a
solution, I would be glad if you can give me some solution.

[image: image.png]
Thanks for your quick response

**Comment by PeopleInside** [comment]
@chanpilli I think GitHub is a place where report bugs or feature requests.

For support you can use the official forum: https://forums.uvdesk.com/ or https://github.com/uvdesk/community-skeleton/discussions

Your issue is that email don't get converted into ticket?
If you open a topic please add more details like the PHP version used, the version of UVdesk used, maybe some steps you followed, screenshots.

If the issue is related to ticket not created when fetching the issue can be wrong site URL.
For example has been discussed here: https://forums.uvdesk.com/topic/2006/not-create-the-ticket-from-email/11
