### ISSUE TITLE
Stuck on Installation

### ISSUE THREAD

**Issue by jenifshrestha** [uvdesk/community-skeleton#341]
I tried installing on AWS platform on Ubuntu. I am stuck at the installation page. Any help !!!

**Comment by papnoisanjeev** [comment]
@jenifshrestha 

It can be because of two reasons.

**1.**  There is no read/write permission for **.env** file of your project (You can enable it by **Chmod 775 -R ./path of .env file**).

**2.**  less **max_exection_time** in your **php.ini** file of your server.  you need to increase it.

Also error will show in **symfony** bar at the bottom of the page.

Finally restart your server and again make a try.

------------------------------------------------------------------------------------------------------------------------------------------

**Or** 

You can try manual method also if above does not work for you !!

Check below link:

https://github.com/uvdesk/community-skeleton/issues/290#issuecomment-661113642
