### ISSUE TITLE
Recaptcha site keys are getting removed when update email settings

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#379]
# Bug report

### Title
Recaptcha site keys are getting removed when update email settings

### Issue Description
when set the keys in uvdesk.yaml and after updating the email setting which update the uvdesk.yaml resets the file and remove keys

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- update the uvdesk with master branch and add recaptcha keys in uvdesk.yaml
    2. step2- update email settings to update uvdesk.yaml.

### Expected result
Recaptcha keys should not be removed if we again update uvdesk.yaml

### Actual result

![Screenshot_329](https://user-images.githubusercontent.com/43210406/112142941-34937d80-8bfd-11eb-80f9-b6d9d526e4ce.png)

![Screenshot_328](https://user-images.githubusercontent.com/43210406/112142294-6526e780-8bfc-11eb-9e1a-467102dec938.png)

**Comment by vaishaliwebkul** [comment]
Seems to be working fine when pull the latest update, as now the Recaptcha manages from the database.

**Comment by PeopleInside** [comment]
@vaishaliwebkul how can I fix also my install that has the zip file patch I receved in the forum?
I'M affected by this bug, how can I fix?
Thanks

**Comment by vaishaliwebkul** [comment]
@PeopleInside 
I suggest you to wait for the latest release then reinstall the application again to avoid any bug in the preinstalled setup.

**Comment by PeopleInside** [comment]
I will be not able to do maybe because of incompatibility with Composer 2 so will need a zip file I think from you.

**Comment by vaishaliwebkul** [comment]
@PeopleInside Of course, if you don't want to start with fresh then we will share the zip file with you after the stable released version so that all the fixes will be added to your project.

**Comment by PeopleInside** [comment]
OK I will wait.
Will be nice if in the stable release you will fix the security issue (on my opinion) related to this:
https://github.com/uvdesk/community-skeleton/issues/310

I need remember to remove this file or remove all permission to avoid potential security issue that can happen if my Mysql.
Also if this is maybe not a security issue because settings are not saved (I never tested) users should not see the wizard to setup a database but an error with Mysql connect.

Thanks for all your support.
