### ISSUE TITLE
Installation struck at step 4-5 while installing

### ISSUE THREAD

**Issue by BATHIVINOD24** [uvdesk/community-skeleton#395]
Installation struck at steps 4-5 while installing " Please wait while your helpdesk is being installed. This could take up to a few minutes. " getting 500 error in development tools

![image](https://user-images.githubusercontent.com/27993980/116009139-7b79f600-a635-11eb-8ac1-9f982242d977.png)

**Comment by papnoisanjeev** [comment]
@BATHIVINOD24 

It may be probably because of two reasons.

-  **.env** of your project have no **read/write** permission please enable it.

 - **max_execution_time** in your **php.ini** file has less **execution** time please increase time and restart your server.

And make a try again after refreshing your URL.

**Comment by papnoisanjeev** [comment]
@BATHIVINOD24 

I hope issue has been resolved so closing it you can still start conversation on same thread if you still facing it.

**Comment by BATHIVINOD24** [comment]
Yes, issue was resolved and working on [#25370](https://support.uvdesk.com/en/customer/ticket/view/25370)
