### ISSUE TITLE
Stable Release v1.0.14 Issue with confirmation or error message

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#420]
Stable Release v1.0.14

When ticket is created the message showed to the user (green message) is no more in Italian.
Now the captcha error is showed on top, how can translate that? Seems the string I have is no more used in translation messages.it.yml

**Comment by vipin-shrivastava** [comment]
@PeopleInside 

Yes ! I found this.
But this is because we want to show  ticket Id in flash message but it is not working. 
If you want to show the flash message in Italian or in any other language just change this line from [here](https://github.com/vipin-shrivastava/core-framework/blob/b8458328386e7d1db119275a4debf5294441d7cc/Controller/Ticket.php#L265) .  
& also we will update this issue in zip.

**Comment by PeopleInside** [comment]
Thank you.
I will close this when I will see the fix in the GitHub official release, until now I will keep the issue open.

**Comment by papnoisanjeev** [comment]
@PeopleInside 
For now updated in core-framework master branch https://github.com/uvdesk/core-framework/commit/abd5a199767fe64e0fa9f0eeb455cdd5963cd41c

**Comment by PeopleInside** [comment]
Sorry, I still have the issue.

**Comment by PeopleInside** [comment]
Resolution here: https://github.com/uvdesk/community-skeleton/issues/424#issuecomment-867747545
