### ISSUE TITLE
can’t upload logo after updating to 1.0.14

### ISSUE THREAD

**Issue by steveb85** [uvdesk/community-skeleton#437]
Server error 500 when uploading LOGO to branding section after installing 1.0.14

### Preconditions
 updated to 1.0.14 

### Actual result
server error 500

**Comment by vipin-shrivastava** [comment]
@steveb85 

Can you please share the screenshot of the error so that we can understand it clearly.

Also, I tried with the latest release, I didn't found such any Issue.

![Screenshot_49](https://user-images.githubusercontent.com/58874186/128120240-f99b77f5-58ee-43a5-a6df-088cfeb5dfc9.png)

As you can see I didn't get any error during uploading the logo in the branding section.

**Comment by steveb85** [comment]
there was a permissions error on the server. it was incorrect owner on assets folder.

**Comment by steveb85** [comment]
not sure why on a fresh install though
