### ISSUE TITLE
V 1.0.15 Default time zone for operator and customer profile should be what is setup on Branding time tab.

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#446]
Issue is not fixed:
https://github.com/uvdesk/community-skeleton/issues/329

The customer see wrong timestamp.
In my branding is set to be DD - MM - YY but customer doesn't find right timestamp because is: MM - DD - YY

![SharedScreenshot](https://user-images.githubusercontent.com/5006150/130405455-b1393d4f-3b70-4f48-a592-d6a9f9c1e50d.jpg)

**Comment by Sanjaybhattwebkul** [comment]
@PeopleInside  This issue is Fixed in our new **release V1.0.16**

![Admin-web](https://user-images.githubusercontent.com/86394952/130444379-23cfba01-88aa-4502-ab92-6ea94b002089.png)
![Branding-admin](https://user-images.githubusercontent.com/86394952/130444385-b9a42ae9-e6a9-4c90-a6a9-eeeff8a77062.png)
![Customer-web](https://user-images.githubusercontent.com/86394952/130444391-90f71de4-2eb2-4321-8f1c-b7482902651a.png)

**Comment by PeopleInside** [comment]
Thanks closing for now, I will check in 1.0.16
