### ISSUE TITLE
swift error

### ISSUE THREAD

**Issue by Pekerche** [uvdesk/community-skeleton#457]
After updating uvdesk to the latest version, the same error always appears, as shown in the image below. The settings are correct and still gives this error. Is it some way? In the case of the update, it just replaces the UVDESK folder with the new one.

![error3](https://user-images.githubusercontent.com/85793019/132252686-61060568-0968-4205-b26f-d0f53a001c52.png)

**Comment by Pekerche** [comment]
error Connection could not be established with host smtp.blueweb.com.br :stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
error:1408F10B:SSL routines:ssl3_get_record:wrong version number

**Comment by vipin-shrivastava** [comment]
@Pekerche 
We are providing encryption on swiftmailer or mailboxes password from the latest version , As you said you have only updated the uvdesk folder, the password which already setups in your mailboxes and swiftmailer  are not encrypted , that's the reason it gives you error .
Update you swiftmailer and mailboxes password then try it again .

**Comment by Pekerche** [comment]
now this error appears: In RefreshMailboxCommand.php line 88:
                                                                  
  Warning: imap_open(): Couldn't open stream imap.blueweb.com.br  
                                                                  

uvdesk:refresh-mailbox [-t|--timestamp TIMESTAMP] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<emails>...]

PHP Fatal error:  Uncaught ErrorException: Notice: Unknown: Can't open mailbox imap.name.com.br: no such mailbox (errflg=2) in Unknown:0
Stack trace:
#0 [internal function]: Symfony\Component\Debug\ErrorHandler->handleError()
#1 {main}
  thrown in Unknown on line 0

**Comment by vipin-shrivastava** [comment]
@Pekerche 
Update your mailbox password, this is because your mailbox password or setting of IMAP is not correct.

**Comment by Pekerche** [comment]
even so the error

**Comment by Pekerche** [comment]
It appears that it is enabled. Ping the imap I put on uvdesk and it responds normal

**Comment by vipin-shrivastava** [comment]
@Pekerche 

Is your swift mailer working now?

Please run the following commands in the given order:
1.` PHP bin/console d:s:u --force`
2.` PHP bin/console c:c`

If your swift mailer is working then check your mailbox setting because this error occurs because of two reason 
1. Less secure app permission '
2. Mailbox setting 

If you still facing the same error please let us know

**Comment by Pekerche** [comment]
still the same error.

**Comment by Pekerche** [comment]
would you have the uvdesk V -1.0.13 folder version?

**Comment by vipin-shrivastava** [comment]
@Pekerche 

Email your helpdesk URL on **support@uvdesk.com** & also mention your issue, our team will help you.

**Comment by PeopleInside** [comment]
@Pekerche if you upgraded UVdesk you need enter in admin side and setup again your email address because now password is encrypted so you must re-insert password in the admin side so the system can save the password encrypted.
The warning say email cannot be sent, maybe because wrong credentials as you maybe never updated account password on UVdesk after the upgrade.

**Comment by vipin-shrivastava** [comment]
@Pekerche 

any update?

**Comment by Komal-sharma-2712** [comment]
We are closing this issue 
if still you are facing issue then you can reply on same mesage thread.
