### ISSUE TITLE
Line breaks are not or not nicely displayed

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#464]
# Bug report

My ticket signature are:

`<p><br /> <br /><strong>Marco Borla</strong> <br />https://helpdesk.peopleinside.it <br />https://www.peopleinside.it</p>`

When I reply to customer ticket all is showed correctly as is showed also on the UVdesk topic from another user here: https://forums.uvdesk.com/topic/1985/1-line-breaks-are-not-or-not-nicely-displayed-2-cryptic-names-in-attachments

When the reply is sent, spaces are not respected and my signature is attached to the reply text that miss all spaces.
The issue is not mail is something in UVdesk

The reply miss text formatting on the web interface and maybe also on emails this means a text like:

Hi, thank you for your message!
Please follow this link: https://link.ext

Thank you

**signature**

Once posted will be:

Hi, thank you for your message! Please follow this link: https://link.ext Thank you
**signature**

Terrible, please fix what is also reported in the UVdesk forum: is the same issue and never depends of customer email, my ticket as been created from the web interface.

Demonstration is easy in the demo.
Please look:

![Uvdesk bug](https://user-images.githubusercontent.com/5006150/132722678-0dcf7926-9b1e-4561-a996-46466e2c5090.gif)

tested with Firefox 92.0 but I don't think is an issue related to the browser!

**Comment by vipin-shrivastava** [comment]
@PeopleInside 

This is happening because of a new fix in UVdesk:
we have already fixed this in master & I also provide you the steps to fix this in your helpdesk :
 1. Open **Thread.php** file  from the given below path in your project : 
 `your_project_name/vendore/uvdesk/core-framework/Controller/Thread.php`
 2. After open **Thread.php** file, Go to line 83 & comment that  & also change the line 90 with following code
   `'message' => str_replace(['&lt;script&gt;', '&lt;/script&gt;'], '', htmlspecialchars($params['reply'])),`

I also added a screenshot after updates of lines
![Screenshot_58](https://user-images.githubusercontent.com/58874186/132737617-05e7f0f1-bfce-418b-a751-f0ab14db0459.png)


Now, you can check your issue is resolved.

If you still facing the same issue please let me know

**Comment by PeopleInside** [comment]
Works, thanks!
