### ISSUE TITLE
There should be proper email validation when the admin is creating a ticket.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [uvdesk/community-skeleton#521]
**Uvdesk Version:** V1.0.18

**Steps To reproduce**--

**1.** Log in as Admin.
**2.** Create a new ticket
**3.** Enter wrong email address
**4.** Click on the Save button

**Expected result:** There should be proper email validation when the admin is creating a ticket.

**Actual result:** There is no proper email validation when the admin is creating a ticket. Please find the screen recording [Here](https://www.awesomescreenshot.com/video/6472508?key=abcffea48b29c0a0173545db688bd784).

**Comment by vipin-shrivastava** [comment]
@Sanjaybhattwebkul 

You can theoretically have an address without a "." in.

Since technically things such as:
user@com
user@localserver
user@[IPv6:2001:db8::1]
Are all valid emails.

So the standard validation allows for all valid E-mails, including the uncommon ones.

For some easy to read explanations (Instead of reading through the standards): http://en.wikipedia.org/wiki/Email_address#Examples

**Comment by Sanjaybhattwebkul** [comment]
@vipin-shrivastava 
As we discuss. this is not an issue. so I am closing this.
