### ISSUE TITLE
Email replies to ticket not visible

### ISSUE THREAD

**Issue by blckhwk** [uvdesk/community-skeleton#558]
# Bug report

### Title
Email replies to ticket not visible

### Issue Description

![image](https://user-images.githubusercontent.com/7903090/163660274-08d7f25c-dd60-4672-aa18-cc1c1dac94b7.png)

### Preconditions
**Please provide as detailed information about your environment as possible.**

UVDesk implementation:

Centos 8
Php 7.4
Nginx 1.14
Composer 2
UVDesk 1.18

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. Create a ticket using create ticket page
    2. the agent post a reply on ticket view thread
    3. the agent also reply to the auto generated email

**Comment by papnoisanjeev** [comment]
@blckhwk 

We can see your editor is not properly loaded here it means any content parsing issue is here due to this you are not able to open other threads on ticket.

Please check you console and most probably it will show where you are facing this issue.

**Or** 

You can create a ticket [here](https://support.uvdesk.com/en/customer/create-ticket/) with all details of your admin panel so the team can check the issue.

So that we can discuss and provide a solution here in case some other users facing the same issue.

**Comment by blckhwk** [comment]
Hi, @papnoisanjeev 

How do check the console? Which logs should I check? 
On the web browser I only see symphony console and there were no errors

Thanks

**Comment by blckhwk** [comment]
issue was resolve by UVdesk support

![image](https://user-images.githubusercontent.com/7903090/164845100-48a2dc47-4fcb-4bc2-91d7-db5394e9f440.png)

**Comment by papnoisanjeev** [comment]
@blckhwk 

Glad to know that you issue has been resolved.
