### ISSUE TITLE
Emails not converting as tickets.

### ISSUE THREAD

**Issue by naseemvk** [uvdesk/community-skeleton#574]
The emails sent to the uvdesk are not converting into tickets.

But refreshing the mailbox is working fine
![image](https://user-images.githubusercontent.com/48643957/172778954-a3426e84-4a93-4270-a678-f24981e2ddca.png)
![image](https://user-images.githubusercontent.com/48643957/172779004-c75d9906-2a2f-4523-8be0-1981f71992d2.png)

Please help us to resolve this issue

**Comment by Komal-sharma-2712** [comment]
@naseemvk 

It may be due to two reasons:

1. **site_url** is not correct.
2. Processing of ticket conversion URL is blocked due to any security reason.

Once check your site URL follow this path:

**uvdesk.yaml**  file **config/packages/uvdesk.yaml**  and find **site_url**, enter the localhost or domain path till public, and make sure you have removed  **http://**

For example: **localhost/folder_name/public**

You can clear the cache with the php command:
**php bin/console c:c**


If you still facing the same issue, let us know.

**Comment by naseemvk** [comment]
Should we include like:

"fqdn/var/www/html/uvdesk/public"

**Comment by Komal-sharma-2712** [comment]
You can see here your site URL:

![image](https://user-images.githubusercontent.com/63539748/172791688-d07d381b-9c05-4197-863c-164d2217630f.png)

**Comment by naseemvk** [comment]
Recently we changed the fqdn of the host. 

Applied the changes in Apache2 sites-avalable, hosts, hostname. After that I think this issue started

This is the url: 
![image](https://user-images.githubusercontent.com/48643957/172796759-6d2ea8c4-0aa1-4830-a740-cdac92a05967.png)

**Comment by naseemvk** [comment]
Anyone please help on this issue

**Comment by Komal-sharma-2712** [comment]
Did you check the Site_URL under **config->packages->uvdesk.yaml** file? Kindly cross-check first and make it for your domain.

If yes, share the screenshot of **uvdesk.yaml** file.

**Comment by vipin-shrivastava** [comment]
@naseemvk  Any update?

**Comment by Komal-sharma-2712** [comment]
We are closing this issue.
If you still facing the same issue you can reply to us on the same thread.
