### ISSUE TITLE
new ticket workflow not working as expected

### ISSUE THREAD

**Issue by NikuyaJS** [uvdesk/community-skeleton#627]
# Bug report

### Issue Description
When a new ticket is created the customer will be notified by email but the 'ticked' agent will not receive an email 

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1.  V -1.1.0
    2. Commit id. - don't know

### Steps to reproduce
Create a new ticket

### Expected result
Ticked agent in workflow should receive email when a new ticket is created

### Actual result

Ticked agent in workflow **doesn't** receive email when a new ticket is created

![uvdesk](https://user-images.githubusercontent.com/79359744/207897911-981b2d07-408d-4493-bc78-3be62ebdd180.png)

**Comment by Komal-sharma-2712** [comment]
@NikuyaJS 


Let us know, you have **created a new workflow** for a created ticket **or updated an existing workflow**. Also, let us know from where you have created a ticket from the admin or customer end:

![image](https://user-images.githubusercontent.com/63539748/208402861-ff4b4ddb-9266-4da4-97de-5de277582603.png)

Because we have checked to create a ticket from the customer end and here are emails going to both sides on the customer and also the agent side:

**=> On the customer email:**

![image](https://user-images.githubusercontent.com/63539748/208405263-74f7d9fc-4173-477f-91dd-ef73e5428d79.png)

**=> On the Agent email:**

![image](https://user-images.githubusercontent.com/63539748/208406810-da0de610-3b7a-4582-833a-a5b826e3b701.png)

**Comment by NikuyaJS** [comment]
@Komal-sharma-2712 

The original workflow had the same issue so deleted it and I recreated my own 'Ticket Created' workflow which has the same issue.

I've checked spam systems and nothing is being blocked. if i was to update the ticket the agent would get a email notification for this.

Is there any logging i can enable to see if the email is being sent to both customer and agent?

**Comment by Komal-sharma-2712** [comment]
@NikuyaJS 

After you have added a new workflow from your side. Let us know from where you have **created a ticket from the admin or customer end**. Also, let us know whether emails receive or not customer side. Only emails not received on the agent email side

**Comment by NikuyaJS** [comment]
@Komal-sharma-2712 

Okay, so the workflow is set up like this
![WF](https://user-images.githubusercontent.com/79359744/209134031-f6cf6c17-c829-4f89-b224-b9af922f99f9.jpg)

If I use http://www.domain.com/en/customer/create-ticket/ the customer and agents DO NOT receive any email notifications for ticket creation

If I send to an email to the uvdesk mailbox only the customer receives an email for ticket creation, the agent that is ticked in workflow does not

**Comment by Komal-sharma-2712** [comment]
@NikuyaJS 

Alright, Please share your helpdesk URL with the login details on our support helpdesk from [here](https://support.uvdesk.com/en/customer/create-ticket/). We will check the error.

**Comment by NikuyaJS** [comment]
@Komal-sharma-2712 

The uvdesk instance isn't publicly accessible. am i able to send screenshots or get some logs to you?

**Comment by Komal-sharma-2712** [comment]
@NikuyaJS 
Alright, create your ticket on our support helpdesk from [here](https://support.uvdesk.com/en/customer/create-ticket/).
