### ISSUE TITLE
Email CC/BCC replies cause new ticket thread

### ISSUE THREAD

**Issue by ghada-charef** [uvdesk/community-skeleton#650]
A reply by CC or BCC email creates a new ticket rather than adding to the thread and the original ticket does not reopen.

Example:
If message written by a user, if response from support with no one in BCC, if response from BCC then the initial ticket does not reopen but it creates a new ticket. If the support responds to this new ticket, the original user receives the response of this new ticket while the support does not see them.

**Comment by Komal-sharma-2712** [comment]
Thanks for reporting, This issue is already uploaded on [here](https://github.com/uvdesk/core-framework/issues/607).
We will try to fixed it in the upcoming future releases. 

For now we are closing this issue because duplicate issue raised. If you are facing any other issue then you can issue raised on over here.
