### ISSUE TITLE
office apps folder missing

### ISSUE THREAD

**Issue by aogheliandlv** [uvdesk/community-skeleton#686]
Hi all! i hope that you are doing well! member/integrations/microsoft-apps/oauth/login is missing when trying to enable office apps.
when i add all the necessary info and hit enter, i get refused to connect 
![Screenshot 2023-07-27 130723](https://github.com/uvdesk/community-skeleton/assets/73615783/ec0ebb13-065c-4305-a74c-18ebbb8ad2ca)
![Screenshot 2023-07-27 130647](https://github.com/uvdesk/community-skeleton/assets/73615783/27a3e355-3b8d-4fde-b43f-70f409ff40c8)

**Comment by Komal-sharma-2712** [comment]
@aogheliandlv 

Let us know, you are using this project on the localhost. If yes, then this **microsoft apps** feature not able to used for localhost. You want use this feature then first you will be installed your project on the server.


Thanks and Regards
Uvdesk Team

**Comment by aogheliandlv** [comment]
i have it installed on a linux server. What server would i need to install it on for office apps to work?

**Comment by Komal-sharma-2712** [comment]
Hello @aogheliandlv ,

When setting up microsoft apps, all you need a HTTPS enabled web server, it doesn't matter which kind of server you're using. This is necessary to carry the microsoft oauth authentication to generate the necessary access credentials. In the provided screenshot, it seems your project is being served through the hostname https://192.168.25.20/. 

You need to make sure that this resource is publicly accessible and able serve your helpdesk project.

You can follow the below blog link:

https://www.uvdesk.com/en/how-to-integrate-microsoft-app-to-your-opensource-uvdesk/

If you have further any query then create a ticket on support panel from [here](https://support.uvdesk.com/en/customer/create-ticket/).

**Comment by simone-gasparini** [comment]
Hello @Komal-sharma-2712,

where can we download the Microsoft App for open-source UVdesk?
From the store is not available to download

**Comment by Komal-sharma-2712** [comment]
Hii @simone-gasparini ,

> Where can we download the Microsoft App for open-source UVdesk? From the store is not available to download

No this app is not available in any store because you can not download the **microsoft app** individual. This microsoft app option added in uvdesk project so you will be just install the uvdesk project and after setup you can use this option. 

But as we have informed to you previous thread that your project should be **installed on server (publicly accessible) or live website** with **https** URL. After that you can use this microsoft app option.

For using the microsoft app you can create a new project using the below command this is not an official release of uvdesk for microsoft app option:

`$ composer create-project uvdesk/community-skeleton:dev-master;`

**Comment by Komal-sharma-2712** [comment]
At this moment, we are closing this issue. If you have further any query or doubt then you can reply on the same issue thread.

Thanks and Regards
Uvdesk Team
